version: "3.7"

#ideas taken from https://knplabs.com/en/blog/how-to-dockerise-a-symfony-4-project

services:
  symfony_app:
    build:
      context: symfony_app
      dockerfile: Dockerfile
    container_name: basicrum_bo_php
    environment:
      - CATCHER_ENDPOINT=http://test11:test22@172.27.0.1/excavator/digger.php
      - MONITORED_ORIGIN=www.darvart.de
    volumes:
      - ./../:/usr/src/app
      - ./symfony_app/.env:/usr/src/app/.env
    depends_on:
      - db
    networks:
      - basicrum_bo_network

  symfony_app_init:
    build:
      context: symfony_app
      dockerfile: Dockerfile
    container_name: symfony_app_init
    volumes:
      - ./../:/usr/src/app
      - ./symfony_app/.env:/usr/src/app/.env
    depends_on:
      - db
    networks:
      - basicrum_bo_network
    command: "sh /usr/src/app/init.sh"

  db:
    image: mysql:8.0.15
    container_name: basicrum_bo_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: basicrum_demo
      MYSQL_USER: roottest
      MYSQL_PASSWORD: roottest
    networks:
      - basicrum_bo_network
    ports:
      - 3308:3306

  nginx:
    image: nginx:1.17-alpine
    container_name: basicrum_bo_nginx
    volumes:
      - ./../public/:/usr/src/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8086:80
    depends_on:
      - symfony_app
    networks:
      - basicrum_bo_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    container_name: basicrum_bo_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: roottest
      PMA_PASSWORD: roottest
    ports:
      - "8087:80"
    networks:
      - basicrum_bo_network
    depends_on:
      - db

networks:
  basicrum_bo_network:
    driver: bridge

